export const AU_MEMBER_STATES = [
    { name: "Algeria", code: "DZA" },
    { name: "Angola", code: "AGO" },
    { name: "Benin", code: "BEN" },
    { name: "Botswana", code: "BWA" },
    { name: "Burkina Faso", code: "BFA" },
    { name: "Burundi", code: "BDI" },
    { name: "Cabo Verde", code: "CPV" },
    { name: "Cameroon", code: "CMR" },
    { name: "Central African Republic", code: "CAF" },
    { name: "Chad", code: "TCD" },
    { name: "Comoros", code: "COM" },
    { name: "Congo, Dem. Rep.", code: "COD" },
    { name: "Congo, Rep.", code: "COG" },
    { name: "Cote d'Ivoire", code: "CIV" },
    { name: "Djibouti", code: "DJI" },
    { name: "Egypt, Arab Rep.", code: "EGY" },
    { name: "Equatorial Guinea", code: "GNQ" },
    { name: "Eritrea", code: "ERI" },
    { name: "Eswatini", code: "SWZ" },
    { name: "Ethiopia", code: "ETH" },
    { name: "Gabon", code: "GAB" },
    { name: "Gambia, The", code: "GMB" },
    { name: "Ghana", code: "GHA" },
    { name: "Guinea", code: "GIN" },
    { name: "Guinea-Bissau", code: "GNB" },
    { name: "Kenya", code: "KEN" },
    { name: "Lesotho", code: "LSO" },
    { name: "Liberia", code: "LBR" },
    { name: "Libya", code: "LBY" },
    { name: "Madagascar", code: "MDG" },
    { name: "Malawi", code: "MWI" },
    { name: "Mali", code: "MLI" },
    { name: "Mauritania", code: "MRT" },
    { name: "Mauritius", code: "MUS" },
    { name: "Morocco", code: "MAR" },
    { name: "Mozambique", code: "MOZ" },
    { name: "Namibia", code: "NAM" },
    { name: "Niger", code: "NER" },
    { name: "Nigeria", code: "NGA" },
    { name: "Rwanda", code: "RWA" },
    { name: "Sahrawi Arab Democratic Republic", code: "ESH" }, // Note: Data might be limited
    { name: "Sao Tome and Principe", code: "STP" },
    { name: "Senegal", code: "SEN" },
    { name: "Seychelles", code: "SYC" },
    { name: "Sierra Leone", code: "SLE" },
    { name: "Somalia", code: "SOM" },
    { name: "South Africa", code: "ZAF" },
    { name: "South Sudan", code: "SSD" },
    { name: "Sudan", code: "SDN" },
    { name: "Tanzania", code: "TZA" },
    { name: "Togo", code: "TGO" },
    { name: "Tunisia", code: "TUN" },
    { name: "Uganda", code: "UGA" },
    { name: "Zambia", code: "ZMB" },
    { name: "Zimbabwe", code: "ZWE" }
];

export const INDICATORS = {
    EXTERNAL_DEBT_STOCKS: 'DT.DOD.DECT.CD',
    EXTERNAL_DEBT_GNI_PCT: 'DT.DOD.DECT.GN.ZS',
    DEBT_SERVICE_EXPORTS_PCT: 'DT.TDS.DECT.EX.ZS',
    DEBT_SERVICE_REVENUE_PCT: 'DUMMY_REVENUE_DATA',
    INTEREST_PAYMENTS: 'DT.INT.DECT.CD',
    GDP_CURRENT_US: 'NY.GDP.MKTP.CD'
};
